#!/lib/bb/sh
set -e
ExitCode=0
while read -r line; do
  case "$line" in 
    */vmlinuz) 
      kdir="/${line%/vmlinuz}"
      kver=${kdir##*/}
      case "$kver" in
        [0-9]*) ;;
        *) continue ;;
      esac
      pkgbase="$kdir/pkgbase"
      [ -f "$pkgbase" ] && read -r kbase < "$pkgbase" || continue
    ;;
    *) continue ;;
  esac
  if diff -q "/${line}" "/boot/vmlinuz-${kbase}" &> /dev/null ; then
    echo "==> Kernel /boot/vmlinuz-${kbase} is up to date."
  else
    echo "==> Installing kernel /boot/vmlinuz-${kbase}"
    install -Dm644 "/${line}" "/boot/vmlinuz-${kbase}"
  fi
  ID=
  for osrel in /usr/lib/os-release /etc/os-release ; do
    [ -f "$osrel" ] || continue
    while read key; do
      case "$key" in
        ID=*) eval "$key" && [ "$ID" ] && break || : ;;
      esac
    done < "$osrel"
    break
  done
  [ "$ID" ] || ID=arch

  ramfs="$ID-$kbase.bbi"
  ramfs=${ramfs/-linux/}

  /usr/share/bbinit/mkramfs "$kver" \
    "/boot/$ramfs" 2>&1 | awk '{printf("==> %s\n",$0)}' 
done



