#!/lib/bb/sh
set -e

while read -r line; do
  case "$line" in 
    */vmlinuz) 
      kdir="/${line%/vmlinuz}"
      kver=${kdir##*/}
      case "$kver" in
        [0-9]*) ;;
        *) continue ;;
      esac
      pkgbase="$kdir/pkgbase"
      [ -f "$pkgbase" ] && read -r kbase < "$pkgbase" || continue
    ;;
    *) continue ;;
  esac
  ID=
  for osrel in /usr/lib/os-release /etc/os-release ; do
    [ -f "$osrel" ] || continue
    while read key; do
      case "$key" in
        ID=*) eval "$key" && [ "$ID" ] && break || : ;;
      esac
    done < "$osrel"
    break
  done
  [ "$ID" ] || continue
  if false ; then rm -f "/boot/vmlinuz-${kbase}"; fi
  ramfs="$ID-$kbase.bbi"
  ramfs=${ramfs/-linux/}
  rm -f "/boot/$ramfs" && exit 0
done

exit 1

