#!/lib/bb/sh
# -*- mode: sh; -*-

[ -f /etc/inittab ] && [ -f /etc/bb.d/conf/inittab ] && \
  ! /lib/bb/busybox diff -q /etc/bb.d/conf/inittab /etc/inittab && \
    /lib/bb/busybox mount --bind /etc/bb.d/conf/inittab /etc/inittab

exec /lib/bb/busybox init $@

