#!/lib/bb/sh
# -*- mode: sh; -*-

export PATH=/sbin:/usr/sbin:/bin:/usr/bin

rcs_main () {

printf 'Beginning %s [%s]\r' "$0" "$$" 1>&2
printf 'Beginning %s [%s]\n' "$0" "$$"

local MODULES_DIR="/lib/modules/$(uname -r)"
local include_file

task_start () { : ; }
for include_file in /etc/bb.d/task/* ; do
  [ -f $include_file ] || continue
  local base_name=/etc/bb.d/task/local/${include_file#*-}
  [ -f $base_name.pre_start ] && . $base_name.pre_start
  [ -f $base_name.mask_start ] && include_file=$base_name.mask_start
  [ -f $include_file ] && . $include_file && task_start
  task_start () { : ; }
  [ -f $base_name.post_start ] && . $base_name.post_start
done

printf 'Leaving %s\r' "$0" 1>&2
printf 'Leaving %s\n' "$0"
}

rcs_main

