#!/lib/bb/sh
# -*- mode: sh; -*-

export PATH=/sbin:/usr/sbin:/bin:/usr/bin

rcs_main () {

printf 'Beginning %s [%s]\r' "$0" "$$" 1>&2
printf 'Beginning %s [%s]\n' "$0" "$$"

local BB='/bin/busybox'
local MODULES_DIR="/lib/modules/$($BB uname -r)"
local include_file

task_start () { : ; }
for include_file in /etc/bb.d/task/* ; do
  [ -f $include_file ] && . $include_file && task_start
  task_start () { : ; }
done

printf 'Leaving %s\r' "$0" 1>&2
printf 'Leaving %s\n' "$0"
}

rcs_main

