#!/lib/bb/sh
# -*- mode: sh; -*-

DEBUG () { echo -en "$@" 1>&2; }

WARN () { printf "*** Warning: %s\n" "$@" 1>&2; }


have_cpu_flag () {
  [ -f /proc/cpuinfo ] && [ -r /proc/cpuinfo ] || return 1
  local Line
  while read Line ; do
    case "$Line" in 
      flags*:*)
        local Flag
        for Flag in $Line ; do
          [ "$Flag" = "$1" ]  && return 0
        done
      ;;
    esac
  done < /proc/cpuinfo
  return 1
}


have_module () {
  local N=$($BB find "$MODULES_SRC_DIR" -type f -name "$1" | $BB wc -l)
  [ "$N" -eq 0 ] && return 1 || return 0
}

get_softdeps () {

  local AllModules=""

  order_module () {
    local M="$1"
    case "$M" in
      crc32c) # If CPU supports SSE 4.2 we can use hardware accel for CRC-32
        if have_cpu_flag 'sse4_2' && have_module 'crc32c[-_]intel.ko*' ; then
          M='crc32c_intel'
        else
          if have_module 'crc32c[-_]generic.ko*' ; then
            M='crc32c_generic'
          fi
        fi
      ;;
    esac
    local E
    for E in $AllModules ; do [ "$E" = "$M" ] && return; done
    AllModules="$AllModules $M"
  }
  local modules_softdep="$MODULES_SRC_DIR/modules.softdep"
  local etc_modules="$1"
  [ -f "$modules_softdep" ] || return
  [ -f "$etc_modules" ] || return 
  local eMod eOpts
  while read eMod eOpts ; do
    eMod=${eMod//-/_}
    local kWord kMod kOpts
    while read kWord kMod kOpts ; do
      [ "$kWord" = 'softdep' ] || continue
      kMod=${kMod//-/_}
      if [ "$eMod" = "$kMod" ] ; then
        local PreMods=""
        local PostMods=""
        local Mode='pre'
        local kOpt
        for kOpt in $kOpts ; do
          case "$kOpt" in
            pre:) Mode='pre' ;;
            post:) Mode='post' ;;
            *) 
              case "$Mode" in
                pre) PreMods="$PreMods $kOpt" ;;
                post) PostMods="$PostMods $kOpt" ;;
              esac
            ;;
          esac
        done
        for M in $PreMods ; do order_module "$M" ; done
        order_module "$eMod"
        for M in $PreMods ; do order_module "$M" ; done
      fi
    done < "$modules_softdep"
    order_module "$eMod"
  done < "$etc_modules"
  echo $AllModules | tr \  \\n > "$2"
}


resolve_softdeps () {
  local etc_modules="$1"
  local etc_modules_tmp="$etc_modules.tmp"
  rm -f "$etc_modules_tmp"
  touch "$etc_modules_tmp"
  local Try=0
  while [ "$Try" -lt 32 ] ; do
    get_softdeps "$etc_modules" "$etc_modules.tmp"
    if diff -q "$etc_modules" "$etc_modules.tmp" > /dev/null ; then
      rm -f "$etc_modules_tmp"
      return 0
    else
      mv "$etc_modules.tmp" "$etc_modules"
      touch "$etc_modules"
    fi
    Try=$((Try+1))
  done
  echo "Warning: unknown error resolving soft module dependencies"
  return 1
}


resolve_alias () {
  case "$@" in
    pci:*) lookup_pci "$@" ;;
    usb:*) lookup_usb "$@" ;;
    *) lookup_etc "$@" ;;
  esac
}


get_deps () {
  local Pattern="/${1//[-_]/[-_]}\.ko\(\.\([gx]z\|zst\)\)*:"
  $BB grep "$Pattern" $MODULES_SRC_DIR/modules.dep | $BB sed -e 's/://' -e 's/ /\n/g'
}



list_modules () {
  local blacklist='./tmp/blacklist'
  local modalias='./tmp/modalias'
  local caselist='./tmp/caselist'
  local case_tmp='./tmp/case_tmp'
  local table='./tmp/table'
  local modlist='./tmp/modlist'
  if [ "$BBI_IGNORE_HOST" != '1' ] ; then
    DEBUG "Generating lookup tables... "
    
    # Exclude blacklisted modules, if any
    if [ -d /etc/modprobe.d/ ] ; then
      $BB cp -r /etc/modprobe.d ./etc/.
      $BB find ./etc/modprobe.d/ -type f -name '*.conf' -exec cat {} + | \
      $BB awk ' /^[ \t]*blacklist[ \t]/ {
        gsub(/[-_]/,"[-_]");
        printf("\\<%s$\n", $2);
      }' > $blacklist
      $BB grep -v -f $blacklist $MODULES_SRC_DIR/modules.alias > $modalias
    else
      $BB cp $MODULES_SRC_DIR/modules.alias $modalias
    fi
    
    # Format each alias into a shell-style case expression
    $BB awk '
    /^alias / {
      sub(/^alias +/,"");
      a=substr($0,1,length($0)-length($NF))
      sub(/ $/,"",a)
      sub(/[-_]/,"[-_]",a)
      gsub(/ /,"\\ ",a)
      gsub(/\(/,"\\(",a)
      gsub(/\)/,"\\)",a)
      printf("%s) echo %s ;;\n",a,$NF);
    }
    ' $modalias | $BB sort -ur > $caselist
    
    # Separate case expressions into three tables for faster lookups
    for sys in pci usb; do
      echo "lookup_$sys () { case \"\$@\" in " > $table.$sys
      $BB grep "^$sys:" $caselist >> $table.$sys
      echo '*) echo $1 ;; esac; }' >> $table.$sys
      . $table.$sys
      $BB grep -v "^$sys:" $caselist > $case_tmp
      $BB mv $case_tmp $caselist
    done
    
    # Anything that's not pci or usb goes into "etc" table
    echo 'lookup_etc () { case "$@" in ' > $table.etc
    $BB cat $caselist >> $table.etc
    echo '*) echo $1 ;; esac; }' >> $table.etc
    . $table.etc
    
    DEBUG "    done.\n"
    
    DEBUG "Scanning /sys for modules... "
    
    # Rummage through the /sys/ directory for module aliases and resolve
    # the actual module filenames, along with any dependencies
    $BB find /sys/ -name modalias -exec $BB cat {} + | $BB sort -u | \
    while read Alias; do
      resolve_alias "$Alias"
    done | $BB sort -u | while read Module; do
      get_deps "$Module"
    done > $modlist
    DEBUG "    done.\n"
  else
   $BB cp $MODULES_SRC_DIR/modules.alias $modalias
   > $modlist
   touch ./etc/autoscan
  fi
  DEBUG "Adding user-specified modules... "
  # Resolve filenames and dependencies for any user-specified modules
  for Module in $BBI_EXTRA_MODULES; do
    get_deps "$Module"
  done >> $modlist
  DEBUG "    done.\n"
  # Send the results to stdout, the caller will deal with it from there
  $BB sort -u $modlist | $BB sed 's#^#'"$KVER/"'#'
}


exclude_module_dir () {
  local module_dir
  for module_dir in $BBI_EXCLUDE_MDIRS ; do
    echo "$1" | $BB grep -q "/$module_dir/" && return 0
  done
  return 1
}


get_host_busybox () {
  if [ "x$BBI_HOST_BUSYBOX" = 'x' ] ; then
    BBI_HOST_BUSYBOX=$(type -p busybox.static) || \
    BBI_HOST_BUSYBOX=$(type -p busybox) 
  fi
  if [ "$BBI_HOST_BUSYBOX" = 'busybox' ] ; then
    BBI_HOST_BUSYBOX=$(which busybox.static) || \
    BBI_HOST_BUSYBOX=$(which busybox) 
  fi
  if [ -f "$BBI_HOST_BUSYBOX" ] && [ -x "$BBI_HOST_BUSYBOX" ] ; then
    BB="$BBI_HOST_BUSYBOX"
  else
    WARN "$0 Cannot find prefered busybox executable, falling back to /bin/busybox"
    BBI_HOST_BUSYBOX='/bin/busybox'
    BB="$BBI_HOST_BUSYBOX"
  fi
}


fix_module_compression () {
  if [ "$BBI_GZIP_MODULES" = '1' ] ; then
    $BB find $MODULES_TRG_DIR/kernel/ -name '*.ko' | $BB sort | \
    while read KO ; do
      $BB gzip $KO
    done
  else
    $BB find $MODULES_TRG_DIR/kernel/ -type f -name '*.ko.*' | $BB sort | \
    while read M ; do
      case $M in
        *.ko.gz)  $BB gzip  -d $M ;;
        *.ko.xz)  $BB xz    -d $M ;;
        *.ko.bz2) $BB bzip2 -d $M ;;
        *.ko.zst) zstd -q -d $M && rm -f $M ;;
        *) WARN "Unsupported file extension:\n $M"
      esac
    done
  fi
}

copy_module () {
  local SRC="$1"
  exclude_module_dir $SRC && return
  [ -e ./lib/modules/$SRC ] && return
  if [ -e "$BBI_MODULES_PATH/$SRC" ] ; then
    $BB install -m 644 -D $BBI_MODULES_PATH/$SRC ./lib/modules/$SRC
  else
    $BB basename "$SRC" >> missing
  fi
}


main () {

  get_host_busybox

  [ "x$BBI_MKRAMFS_CONF"  =  'x' ] && \
    BBI_MKRAMFS_CONF='/etc/bb.d/conf/mkramfs.conf'

  # We want current environment variables to take precedence over
  # config file, so save current env to file, load config, re-load saved env.
  if [ -f "$BBI_MKRAMFS_CONF" ] && [ -r "$BBI_MKRAMFS_CONF" ] ; then
    local ENV_TMP=$($BB mktemp /tmp/bbinit_env.XXXXXX)
    set > "$ENV_TMP"
    . "$BBI_MKRAMFS_CONF"
    . "$ENV_TMP"
    $BB rm -f "$ENV_TMP"
  fi

  # Fallbacks in case these still aren't set
  : ${BBI_COMPRESSOR:=gzip}
  : ${BBI_EXCLUDE_MDIRS:=cpufreq gpu hotplug kvm sound watchdog}
  : ${BBI_EXTRA_MODULES:=ext2 ext3 ext4}
  : ${BBI_IGNORE_HOST:=0}
  : ${BBI_MODULES_PATH:=/lib/modules}
  : ${BBI_RAMFS_BUSYBOX:=$BB}
  : ${BBI_RAMFS_INIT:=$($BB dirname $($BB readlink -f $0))/init}
  : ${BBI_RAMFS_NAME:=ramfs}
  : ${BBI_EXTRA_FILES_ROOT:=/}
  : ${BBI_GZIP_MODULES:=0}

  local TOPDIR=$($BB mktemp -td initramfs.XXXXXX)

  [ -z "$KVER" ] && KVER=$($BB uname -r)

  MODULES_SRC_DIR="$BBI_MODULES_PATH/$KVER"
  MODULES_TRG_DIR="./lib/modules/$KVER"

  case "$BBI_RAMFS_NAME" in 
    */*) ;;
    *) BBI_RAMFS_NAME="/boot/$BBI_RAMFS_NAME" ;;
  esac
  cd $TOPDIR || exit
  $BB mkdir bin dev etc lib proc sys tmp usr usr/bin usr/sbin var
  $BB cp $BBI_RAMFS_BUSYBOX bin/busybox
  $BB chmod 755 bin/busybox
  $BB cp $BBI_RAMFS_INIT ./init
  $BB chmod 755 ./init
  for SRC in $(list_modules) ; do copy_module "$SRC" ; done
  if [ "$BBI_IGNORE_HOST" != '1' ] ; then
    $BB find "$MODULES_TRG_DIR/kernel/" -name '*.ko*'  | $BB sort | \
    while read KO ; do
      KO=${KO##*/}
      echo ${KO%.ko*}
    done > etc/modules
    DEBUG "Resolving soft dependencies...     "
    resolve_softdeps etc/modules
    while read Module ; do
      get_deps "$Module"
    done < etc/modules | $BB sed 's#^#'"$KVER/"'#' | while read SRC ; do
      copy_module "$SRC"
    done
    DEBUG "done.\n"
  fi
  fix_module_compression
  if [ -e missing ] ; then
    for M in $($BB sort -u missing) ; do 
      WARN "missing module '$M'"
    done
    $BB rm -f missing
  fi

  for EXT in builtin alias dep; do
    F=$MODULES_SRC_DIR/modules.$EXT 
    [ -e $F ] && $BB cp $F $MODULES_TRG_DIR/
  done

  case "$BBI_EXTRA_FILES_ROOT" in
    */.) ;;
    */) BBI_EXTRA_FILES_ROOT="$BBI_EXTRA_FILES_ROOT." ;;
    *) BBI_EXTRA_FILES_ROOT="$BBI_EXTRA_FILES_ROOT/."
  esac
  if [ -d "$BBI_EXTRA_FILES_ROOT" ] ; then
    for F in $BBI_EXTRA_FILES ; do
      case "$F" in
       /*) 
         local D=.$($BB dirname "$F")
         $BB mkdir -p "$D"
         $BB yes n | $BB cp -ai "$BBI_EXTRA_FILES_ROOT$F" "$D"
       ;;
       *)
         WARN "BBI_EXTRA_FILES paths must begin with / (skipping $F)"
       ;;
      esac
    done
  else
    WARN "BBI_EXTRA_FILES_ROOT path not found: $BBI_EXTRA_FILES_ROOT"
  fi

  [ -e etc/mdev.conf ] || \
  echo '$MODALIAS=.* 0:0 660 @modprobe "$MODALIAS" 2> /dev/null' > etc/mdev.conf

  # Minimal profile for rescue shell
  [ -e etc/profile ] || \
cat << EOF > etc/profile
alias reboot='sync; reboot -f'
alias poweroff='sync; poweroff -f'
alias halt='sync; halt -f'
EOF

  [ -f "$BBI_FIXUP" ] && [ -x "$BBI_FIXUP" ] && $BBI_FIXUP

  DEBUG "Creating \"$BBI_RAMFS_NAME\"; $BBI_COMPRESSOR format... "
  $BB find . | $BB grep -v '\./tmp/..*' | $BB cpio -H newc -o | \
    $BBI_COMPRESSOR > $BBI_RAMFS_NAME
  DEBUG "done.\n"
  DEBUG $(
    printf 'Created "%s" (%s entries, %sMB)\n' \
    $BBI_RAMFS_NAME \
    $($BB find . | $BB grep -v '\./tmp/..*' | $BB wc -l) \
    $($BB stat -c %s $BBI_RAMFS_NAME | \
    $BB awk '{printf("%0.2f\n", $1/(1024*1024))}')
  )'\n'
  [ "$BBI_KEEP_TMPFILES" = '1' ] || $BB rm -r $TOPDIR
}


KVER=$1
[ "x$2" = 'x' ] || BBI_RAMFS_NAME=$2

main

