#!/lib/bb/sh
# -*- mode: sh; -*-

# Change device's group ownership to $1, then execute remaining args.
[ "x$1" != 'x' ] && [ -e "$MDEV" ] || exit 1
[ "$ACTION" = 'add' ] && [ -f /etc/group ] && \
grep -q "^$1:" /etc/group && chgrp "$1" "$MDEV"
[ $# -gt 1 ] && shift && exec $@

