#!/bin/busybox sh
# -*- mode: sh; -*-

# The kmod version of modprobe silently ignores requests to load a 
# built-in module, but busybox modprobe complains. Make it stop.

[ $# -eq 0 ] && exit 1
BB='/bin/busybox'
f=/lib/modules/$($BB uname -r)/modules.builtin
if [ -f "$f" ] && $BB grep -q "/$1\.ko$" "$f"; then
  ($BB modprobe "$1" 2>&1 | ($BB grep -v '\<not found\>' 1>&2))
else
  exec $BB modprobe $@
fi

