
Update is complete.

Please check the /etc/bb.d and /usr/share/bbinit folders for
any *.new or *.old files.

The *.new files are newly updated, but did not replace existing 
user-modified configuration files.

The *.old files are user-modified files from a previous installation
that have been replaced by files from this update. 

The *.new and *.old files can probably be safely deleted, but
you might want to update your initramfs file and reboot first,
just to make sure everything still works as expected.

