#!/lib/bb/sh
# -*- mode: sh; -*-

[ -f /etc/bb.d/conf/autologin.conf ] && . /etc/bb.d/conf/autologin.conf

# If no username is specified, fallback to normal login prompt
[ "x$AUTOLOGIN" = 'x' ] && exec getty 0 -l login tty1

# If username is '?' try to find "autologin=" on kernel command line
if [ "$AUTOLOGIN" = '?' ] && [ -r '/proc/cmdline' ]; then
  for A in $(cat '/proc/cmdline') ; do
     case "$A" in
       autologin=*) 
         AUTOLOGIN=${A#*=}
         break
       ;;
     esac
  done
fi

# If numeric value, consider it as a UID
if printf '%d' "$AUTOLOGIN"  &> /dev/null ; then
  AUTOLOGIN=$(
    awk -F : '{if ( $3 == "'$AUTOLOGIN'") {print $1}}' /etc/passwd
  )
fi

# If username is invalid, fallback to normal login prompt
id -u "$AUTOLOGIN" &> /dev/null || exec getty 0 tty1

exec login -f "$AUTOLOGIN"

