#!/lib/bb/sh

TopDir='/sys/fs/cgroup'
MntOpts='nodev,noexec,nosuid'
RcName='openrc'
RcDir="$TopDir/$RcName"

if [ $# -eq 0 ] ; then # Mount the logind (openrc) namespace...
  HaveCG=false
  while read nodev fs ; do
    [ "$nodev" = 'nodev' ] && [ "$fs" =  'cgroup' ] && HaveCG=true && break
  done < /proc/filesystems
  if ! $HaveCG; then 
    logger -s -t bbinit daemon.warn 'Kernel does not support cgroups'
    exit 1
  fi
  mountpoint -q "$TopDir" ||
    mount -t tmpfs -o "$MntOpts,mode=755,size=10m" cgroup_root $TopDir
  mountpoint -q "$RcDir" && exit 0
  RelAgnt="release_agent="$(readlink -f "$0")
  mkdir -p "$RcDir"
  mount -t cgroup -o "none,$MntOpts,name=$RcName,$RelAgnt" $RcName "$RcDir"
  printf 1 > "$RcDir/notify_on_release"  
else # Here we act as the "release_agent" when logind unmounts a subdir...
  Dir="$RcDir/$1"
  [ -d "$Dir" ] && rmdir "$Dir"
fi

